### ISSUE TITLE
Error "No python interpreter configured for the project"

### ISSUE THREAD

**Issue by jjanicik** [ttruty/QualtricsMailer#1]
First of all, thank you for providing this project.  I tried unsuccessfully to get the original project from Kai Analytics to run.

I followed your Read me instructions and input all of my Qualtrics ids and am trying to run the main.py script.

At the top of the header bar is the following:

"No python interpreter configured for the project"

After running, I get the following error in the box below:

"C:\Users\Jim Janicik\PycharmProjects\getting_started\venv\Scripts\python.exe" X:/Qualtrics_API/QualtricsMailer/main.py
Traceback (most recent call last):
  File "X:/Qualtrics_API/QualtricsMailer/main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Process finished with exit code 1

Please advise.

**Comment by ttruty** [comment]
It appears that you do not have the "requests" module dependency installed.
You can install with the command in the console. 
`pip install requests` 
or
`pip3 install requests`
depending on your environment and that you have pip installed
Here is a tutorial on pip
https://www.datacamp.com/community/tutorials/pip-python-package-manager

**Comment by ttruty** [comment]
As for the "No python interpreter configured for the project"
If you are using pycharm, you need to set the python runtime to run the code.
This shows you how to do that 
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html

**Comment by jjanicik** [comment]
Timothy,

	Thank you for the both of the links that you sent.

	I was able to resolve both issues and successfully run a test email
distribution.

	This allows me to move forward with development with a project that
has been delayed for a few months now.

	Enjoy the rest of your weekend.

	Jim

	-----------------------------------------From: "Timothy Truty" 
To: "ttruty/QualtricsMailer"
Cc: "jjanicik", "Author"
Sent: Friday November 29 2019 9:57:58AM
Subject: Re: [ttruty/QualtricsMailer] Error "No python interpreter
configured for the project" (#1)

	As for the "No python interpreter configured for the project"
 If you are using pycharm, you need to set the python runtime to run
the code.
 This shows you how to do that
 
[1]https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
[2] 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4]. 

Links:
------
[1]
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
[2]
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
[3]
https://github.com/ttruty/QualtricsMailer/issues/1?email_source=notifications&email_token=AAH75RIDS6KD5M2HQJJHYQDQWE3YNA5CNFSM4JSVMMPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPFSDA#issuecomment-559831308
[4]
