### ISSUE TITLE
Qualtrics API V3 Compliancy

### ISSUE THREAD

**Issue by jjanicik** [ttruty/QualtricsMailer#3]
Timothy,

Are all of the direct API calls made to Qualtrics  version 3?

I am asking because Qualtrics V2 call will be deprecated on 3/31/2020.

Thanks,

Jim

**Comment by ttruty** [comment]
Hey Jim,
Thanks for the info, I did not know about the V2 to V3 migration. Tool is set up using v3 see line here: https://github.com/ttruty/QualtricsMailer/blob/ad1ca27171c06ae4b7262f61139e46eef542c276/main.py#L79

**Comment by jjanicik** [comment]
Thank for confirming that it is V3.
